# Generated by Django 5.2.10 on 2026-04-13 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompraMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Ano')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Lista de compra mensal',
                'verbose_name_plural': 'Listas de compra mensais',
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('mes', 'ano'), name='unique_mes_ano_lista_compra')],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do item')),
                ('quantidade', models.CharField(blank=True, max_length=50, verbose_name='Quantidade')),
                ('comprado', models.BooleanField(default=False, verbose_name='Comprado')),
                ('observacao', models.CharField(blank=True, max_length=150, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.listacompramensal', verbose_name='Lista')),
            ],
            options={
                'verbose_name': 'Item de compra',
                'verbose_name_plural': 'Itens de compra',
                'ordering': ['comprado', 'nome'],
            },
        ),
    ]
